language: php
php:
- 5.4
before_script:
- composer install --dev --prefer-dist
script:
- php .travis/phppec.php component/ plugins/ # Parse error checker
- php .travis/phpcs.php # Code Sniffer Checker
- php .travis/phpmd.php # Mess detector Checker
notifications:
  slack: redweb:7hTS3MPEBxt3lkVopUcVPJKa