ALTER TABLE `#__rwf_billinginfo` CHANGE `address` `address` TEXT;
ALTER TABLE `#__rwf_billinginfo` CHANGE `params` `params` TEXT;
ALTER TABLE `#__rwf_fields` CHANGE `params` `params` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `submissionbody` `submissionbody` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `admin_notification_email_body` `admin_notification_email_body` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `confirmation_notification_recipients` `confirmation_notification_recipients` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `confirmation_contactperson_body` `confirmation_contactperson_body` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `notificationtext` `notificationtext` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `paymentprocessing` `paymentprocessing` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `paymentaccepted` `paymentaccepted` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `contactpaymentnotificationsubject` `contactpaymentnotificationsubject` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `contactpaymentnotificationbody` `contactpaymentnotificationbody` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `submitterpaymentnotificationsubject` `submitterpaymentnotificationsubject` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `submitterpaymentnotificationbody` `submitterpaymentnotificationbody` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `cond_recipients` `cond_recipients` TEXT;
ALTER TABLE `#__rwf_forms` CHANGE `params` `params` TEXT;
ALTER TABLE `#__rwf_submitters` CHANGE `rawformdata` `rawformdata` TEXT;
ALTER TABLE `#__rwf_payment_request` CHANGE `note` `note` TEXT;
ALTER TABLE `#__rwf_cart` CHANGE `note` `note` TEXT;
ALTER TABLE `#__rwf_payment` CHANGE `data` `data` TEXT;
ALTER TABLE `#__rwf_section` CHANGE `description` `description` TEXT;
ALTER TABLE `#__rwf_section` CHANGE `checked_out` `checked_out` int(11) NULL;
ALTER TABLE `#__rwf_values` CHANGE `checked_out` `checked_out` int(11) NULL;
ALTER TABLE `#__rwf_forms` CHANGE `checked_out` `checked_out` int(11) NULL;
ALTER TABLE `#__rwf_fields` CHANGE `checked_out` `checked_out` int(11) NULL;
